services:
  db:
    image: postgres:15.6
    container_name: todo-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - todo-postgres:/var/lib/postgresql/data
    networks:
      - todo-backend
    env_file:
      - .env
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "${DB_DATABASE}",
          "-U",
          "${DB_USERNAME}",
        ]
      interval: 10s
      retries: 3
      timeout: 5s
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: todo-adminer
    networks:
      - todo-backend
      - todo-frontend
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer-http.rule=Host(`db.cv01.davidessien.com`) || Host(`www.db.cv01.davidessien.com`)
      - traefik.http.routers.adminer-http.entrypoints=web
      - traefik.http.services.adminer-http.loadbalancer.server.port=8080
      - traefik.http.routers.adminer-https.middlewares=www-to-non-www
      - traefik.http.routers.adminer-https.rule=Host(`db.cv01.davidessien.com`) || Host(`www.db.cv01.davidessien.com`)
      - traefik.http.routers.adminer-https.entrypoints=websecure
      - traefik.http.routers.adminer-https.tls.certresolver=staging
    depends_on:
      db:
        condition: service_healthy

volumes:
  todo-postgres:
    driver: local
