include:
  - ./db.compose.yml
  - ./monitoring.compose.yml
  - ./traefik.compose.yml

services:
  todo-api:
    build:
      context: ./todo-api
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "8000:8000"
    networks:
      - todo-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api-http.rule=((Host(`cv01.davidessien.com`)  || Host(`www.cv01.davidessien.com`)) && (PathPrefix(`/api`) || PathPrefix(`/redoc`) || PathPrefix(`/docs`)))"
      - "traefik.http.routers.api-http.entrypoint=web"
      - "traefik.http.services.api-http.loadbalancer.server.port=8000"
      - "traefik.http.routers.api-https.rule=(Host(`cv01.davidessien.com`) && (PathPrefix(`/api`) || PathPrefix(`/redoc`) || PathPrefix(`/docs`)))"
      - "traefik.http.routers.api-https.middlewares=redirect-to-non-www"
      - "traefik.http.routers.api-https.entrypoints=websecure"
      - "traefik.http.routers.api-https.tls.certresolver=staging"
    env_file:
      - ./todo-api/.env
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--spider",
          "http://localhost:8000/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:3000"
    networks:
      - todo-frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-http.rule=(Host(`cv01.davidessien.com`) || Host(`www.cv01.davidessien.com`))"
      - "traefik.http.routers.frontend-http.entrypoints=web"
      - "traefik.http.services.frontend-http.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend-https.middlewares=redirect-to-non-www"
      - "traefik.http.routers.frontend-https.rule=(Host(`cv01.davidessien.com`) || Host(`www.cv01.davidessien.com`))"
      - "traefik.http.routers.frontend-https.entrypoints=websecure"
      - "traefik.http.routers.frontend-https.tls.certresolver=staging"
    restart: unless-stopped

networks:
  todo-frontend:
    name: todo-frontend
    driver: bridge
  todo-backend:
    name: todo-backend
    driver: bridge
  monitoring:
    name: monitoring
    driver: bridge
