include:
  - ./db.compose.yaml
  - ./monitoring.compose.yaml
  - ./traefik.compose.yaml

services:
  todo-api:
    build:
      context: ./todo-api
      dockerfile: Dockerfile
    container_name: todo-api
    ports:
      - "8000:8000"
    networks:
      - todo-backend
    labels:
      - traefik.enabled=true
      - traefik.http.routers.api.rule=Host(`api.davidessien.com`) && PathPrefix(`/api`)
      - traefik.http.services.api.loadbalancer.server.port=8000
      - traefik.http.routers.api.entrypoint=web
      - traefik.http.routers.docs.rule=Host(`api-docs.davidessien.com`) && PathPrefix(`/docs`)
      - traefik.http.services.docs.loadbalancer.server.port=8000
      - traefik.http.routers.docs.entrypoint=web
    env_file:
      - ./todo-api/.env
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--spider",
          "http://localhost:8000/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      db:
        condition: service_healthy

  todo-frontend:
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "3000:3000"
    networks:
      - todo-frontend
    labels:
      - traefik.enabled=true
      - traefik.http.routers.frontend.rule=Host(`frontend.davidessien.com`)
      - traefik.http.routers.frontend.entrypoints=web
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    restart: unless-stopped

networks:
  todo-frontend:
    external: true
  todo-backend:
    external: true
