services:
  reverse-proxy:
    image: traefik:v3.2.1
    container_name: traefik
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`cv01.davidessien.com`) && PathPrefix(`/traefik`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.services.traefik.loadbalancer.server.port=80
    volumes:
      - ./reverse-proxy/traefik.yaml:/etc/traefik/traefik.yml:ro # Traefik's main configuration file
      - /var/run/docker.sock:/var/run/docker.sock:ro # Access Docker socket
      - ./letsencrypt:/letsencrypt # Persistent certificate storage
    networks:
      - todo-frontend
      - todo-backend
      - monitoring
