auth_enabled: false # Disable authentication (adjust if needed for security)

server:
  http_listen_port: 3100 # Loki's API port for receiving logs

distributor:
  ring:
    kvstore:
      store: inmemory # Using in-memory key-value store (no high availability needed)
    consistent_hash_ring:
      num_tokens: 256 # Number of tokens for better distribution (can be adjusted)

ingester:
  chunk_target_size: 1048576 # 1MB per chunk (can be adjusted based on log size)
  max_chunk_age: 1h # Max age of log chunks (logs older than this will be compacted)
  lifecycler:
    ring:
      kvstore:
        store: inmemory # Keeping the ring in memory
      replication_factor: 1 # No replication, since this is a single-node setup

querier:
  query_timeout: 1m # Timeout for queries (adjust based on your query volume)
  max_concurrent: 50 # Limit number of concurrent queries (can be adjusted based on traffic)

frontend:
  log_queries_fully_completed: true # Enable logging for query completion

storage_config:
  boltdb_shipper:
    active_index_directory: /data/loki/index # Location for index data
    cache_location: /data/loki/cache # Location for cache data
    storage_type: filesystem # Store logs on the local filesystem
    directory: /data/loki/chunks # Location for log chunks on the disk

limits_config:
  max_entries_limit: 500000 # Maximum number of entries per query
  max_chunk_size: 1048576 # Max size for a log chunk (1MB)

chunk_target_size: 1048576 # Max size of each log chunk
