server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: "http://loki:3100/loki/api/v1/push"

scrape_configs:
  - job_name: "system_logs"
    static_configs:
      - targets: ["localhost"]
        labels:
          job: "system_logs"
          __path__: /var/log/*log

  - job_name: "docker_logs"
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
        refresh_interval: 10s
    relabel_configs:
      - source_labels: [__meta_docker_container_name]
        target_label: job
        replacement: "docker_logs"
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
      - source_labels: [__meta_docker_container_name]
        regex: "/(.+)"
        target_label: container_name
      - source_labels: [__meta_docker_container_name]
        regex: (.+)
        target_label: __path__
        replacement: "/var/lib/docker/containers/$1/$1-json.log"
