server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: "http://loki:3100/loki/api/v1/push"

scrape_configs:
  # System logs job
  - job_name: "system_logs"
    static_configs:
      - targets:
          - "localhost"
        labels:
          job: "system_logs"
          __path__: /var/log/*log

  - job_name: docker-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker-logs
          __path__: /var/lib/docker/containers/*/*.log

    relabel_configs:
      # Extract container ID and container name
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

      - source_labels: [__meta_docker_container_name]
        regex: "/(.+)"
        target_label: container_name

      # Assign the correct path to container logs
      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: "/var/lib/docker/containers/$1/$1-json.log"

      # Optional: Filter out containers if needed (e.g., exclude Promtail itself)
      - source_labels: [__meta_docker_container_name]
        regex: "promtail"
        action: drop
