server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/log/positions.yaml

clients:
  - url: "http://loki:3100/loki/api/v1/push"

scrape_configs:
  # System logs
  - job_name: "system_logs"
    static_configs:
      - targets:
          - "localhost"
        labels:
          job: "system_logs"
          __path__: /var/log/*.log

  # Docker Service Discovery
  - job_name: "docker_logs"
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
    relabel_configs:
      # Extract container ID from the discovered targets
      - source_labels: [__meta_docker_container_id]
        target_label: container_id

      # Extract container name and use it as a label
      - source_labels: [__meta_docker_container_name]
        regex: "/(.+)"
        target_label: container_name

      # Assign path to container logs
      - source_labels: [__meta_docker_container_id]
        target_label: __path__
        replacement: "/var/lib/docker/containers/$1/$1-json.log"

      # Optional: Drop logs from specific containers
      - source_labels: [__meta_docker_container_name]
        regex: "promtail"
        action: drop
