# Traefik Global Configuration
api:
  dashboard: true
  insecure: false # Ensure the dashboard is secured

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: myresolver

providers:
  docker:
    exposedByDefault: false # Ensure only explicitly labeled containers are exposed
    network: todo-frontend # Replace with the appropriate Docker network

certificatesResolvers:
  myresolver:
    acme:
      email: davidessienshare@gmail.com # Replace with your email for certificate registration
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web

log:
  level: INFO # Log level (DEBUG, INFO, WARN, ERROR)

accessLog: # Enables access logging
  filePath: /var/log/traefik/access.log
  bufferingSize: 100 # Optional: Number of access logs to buffer before writing

metrics:
  prometheus:
    entryPoint: websecure # Expose Prometheus metrics on the websecure endpoint
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
