# Traefik Global Configuration
api:
  dashboard: true
  insecure: false # Ensure the dashboard is secured

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: staging

middlewares:
  redirect-to-non-www:
    redirectRegex:
      regex: "^https?://www\\.(.+)"
      replacement: "https://$1"
      permanent: true

providers:
  docker:
    exposedByDefault: false # Ensure only explicitly labeled containers are exposed

certificatesResolvers:
  staging:
    acme:
      email: davidessienshare@gmail.com
      storage: /letsencrypt/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
  production:
    acme:
      email: davidessienshare@gmail.com
      storage: /letsencrypt/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

log:
  level: INFO # Log level (DEBUG, INFO, WARN, ERROR)

accessLog: # Enables access logging
  filePath: /var/log/traefik/access.log
  bufferingSize: 100 # Optional: Number of access logs to buffer before writing

metrics:
  prometheus:
    entryPoint: websecure # Expose Prometheus metrics on the websecure endpoint
    addEntryPointsLabels: true
    addServicesLabels: true
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
